CREATE TABLE IF NOT EXISTS parent_admin
(
 family_id        int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 parent_name      text NOT NULL,
 parent_username  text NOT NULL,
 password         text NOT NULL,
 user_type        text NOT NULL,
 parent_user_id   int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 family_last_name text NOT NULL,
 CONSTRAINT PK_user PRIMARY KEY ( family_id )
);




