CREATE TABLE children
(
 child_id  int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 family_id int NOT NULL,
 full_name text NOT NULL,
 username  text NOT NULL,
 user_type text NOT NULL,
 password  text NOT NULL,
 age       int NOT NULL,
 gender    text NOT NULL,
 tokens    int NOT NULL,
 CONSTRAINT PK_children PRIMARY KEY ( child_id ),
 CONSTRAINT FK_24 FOREIGN KEY ( family_id ) REFERENCES parent_admin ( family_id )
);

CREATE INDEX fkIdx_25 ON children
(
 family_id
);